Argo cd external link
komodorio/docs pull request #104
Opened 2022-08-06 20:03 UTC by oded-komodor

Add a tutorial that demonstrates how to integrate ArgoCD external link to the Komodor
based on the Kubernetes workload resources annotation to extend Argo’s functionality

2022-08-11 10:56 UTC, amit9192 requested changes

2022-08-11 10:56 UTC, amit9192 commented on docs/Integrations/ArgoCD.md
> +
@oded-komodor - Add title?

2022-08-11 10:56 UTC, amit9192 commented on docs/Integrations/ArgoCD.md
> + \
This extra \ is going to be presented on the page - you should probably drop it :)

2022-08-11 10:56 UTC, amit9192 commented on docs/Integrations/ArgoCD.md
> +gain effectively investigate Kubernetes issues providing a clear understanding of all events and historical context across a timeline. \
Is that a new sentence or part of the previous one?

2022-08-11 10:56 UTC, amit9192 commented on docs/Integrations/ArgoCD.md
> +This tutorial demonstrates how to integrate ArgoCD external link to the Komodor application for using Komodor as a centralized troubleshooting platform that allows users
Suggestion: This tutorial demonstrates how to utilize ArgoCD external links (+ make it a URL - https://argo-cd.readthedocs.io/en/stable/user-guide/external-url/) to link to the Komodor platform...

2022-08-11 10:56 UTC, amit9192 commented on docs/Integrations/ArgoCD.md
> +gain effectively investigate Kubernetes issues providing a clear understanding of all events and historical context across a timeline. \
Komodor allows users to effectively investigate Kubernetes-related issues by providing a clear understanding of all events and...

2022-08-11 10:56 UTC, amit9192 commented on docs/Integrations/ArgoCD.md
> + \
You go down two lines here (see the preview)

2022-08-14 09:48 UTC, oded-komodor commented
closing PR and adding a new MD file

2022-08-14 09:48 UTC, closed without merging