Updates to Annotations
komodorio/docs pull request #157
Opened 2023-03-08 15:31 UTC by hughbrien

Updated the Annotations Documentation to add some clarification and specificity

2023-03-08 15:35 UTC, ronahk commented on docs/Learn/Annotations.md
> +- Source Control like Git,
Is the comma here correct?

2023-03-08 15:35 UTC, ronahk commented on docs/Learn/Annotations.md
> +- DevOps tools,
Same here

2023-03-08 15:44 UTC, ronahk commented on docs/Learn/Annotations.md
> +Komodor uses these annotations enrich service information and creates powerful connections between services.
to enrich?

2023-03-08 15:45 UTC, ronahk commented on docs/Learn/Annotations.md
> +Annotation links have  different types:
extra space here

2023-03-08 15:46 UTC, ronahk reviewed
Looks good, some minor comments/questions.

2023-03-08 19:03 UTC, hughbrien commented on docs/Learn/Annotations.md
> +- Source Control like Git,
Removed

2023-03-08 19:03 UTC, hughbrien commented on docs/Learn/Annotations.md
> +- DevOps tools,
Removed from original source

2023-03-08 19:04 UTC, hughbrien commented on docs/Learn/Annotations.md
> +Komodor uses these annotations enrich service information and creates powerful connections between services.
If you want to removed it you can but here is the meaning : 

enrich : transitive verb : To make fuller, more meaningful, or more rewarding.

2023-03-10 18:03 UTC, hughbrien commented on docs/Learn/Annotations.md
> +Komodor uses these annotations enrich service information and creates powerful connections between services.
Yes. if it's an obvious typo please fix it : )

2023-03-13 09:40 UTC, ronahk approved these changes

2023-03-16 08:09 UTC, gxxglyeyez requested changes

2023-03-16 08:09 UTC, gxxglyeyez commented on docs/Learn/Annotations.md
> +Komodor annotations enable users to create static and dynamic hyperlinks to other solutions and resources.
@hughbrien I don't think that we should limit it only to hyperlinks.
We might want to add alert configuration via annotations or custom filters

2023-03-27 14:23 UTC, hughbrien commented on docs/Learn/Annotations.md
> +Komodor annotations enable users to create static and dynamic hyperlinks to other solutions and resources.
I am not sure what this means. Are saying we can "link to screens in Komodor"?  or other Solutions? 
"We might want to add alert configuration via annotations or custom filters"

2023-03-28 18:44 UTC, hughbrien commented
Can We move these changes forward.

2023-04-10 17:50 UTC, hughbrien commented
I would like to get changes published.  If you have an issue with any of them. Just reject or update them.

2023-04-11 06:44 UTC, gxxglyeyez approved these changes

2023-04-11 06:44 UTC, merged