Update mkdocs.yml
komodorio/docs pull request #27
Opened 2021-11-10 13:00 UTC by gxxglyeyez

Added new page

2021-11-10 13:52 UTC, MickaelAlliel requested changes

2021-11-10 13:52 UTC, MickaelAlliel commented on mkdocs.yml
> +    - Micosoft Teams: Integrations/MicrosoftTeams.md
```suggestion
    - Microsoft Teams: Integrations/MicrosoftTeams.md
```

2021-11-10 14:33 UTC, guymenahem approved these changes

2021-11-11 14:09 UTC, angus-young approved these changes

2021-11-14 07:28 UTC, olegsu approved these changes

2021-11-14 07:33 UTC, merged